cliente:
  image:
    repository: rgallardj/actividad1
    tag: gestioncliente-latest
  replicaCount: 1
  service:
    port: 8092  # Puerto deseado para el servicio de cliente
    nodePort: 30030
    type: NodePort  # o el tipo de servicio que desees

serviceAccount:
  create: false  # O establece esto en false si no quieres crear un nuevo ServiceAccount
  # Otras configuraciones del service account si las tienes
