apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  replicas: {{ .Values.cliente.replicaCount }}
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-cliente
          image: "{{ .Values.cliente.image.repository }}:{{ .Values.cliente.image.tag }}"
          ports:
            - name: http
              containerPort: 8092
              protocol: TCP
          # ... otras configuraciones del contenedor cliente ...
