# mi-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  replicas: {{ .Values.cliente.replicaCount }}
  selector:
    matchLabels:
        app: client-app
  template:
    metadata:
      labels:
          app: client-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-cliente
          image: "{{ .Values.cliente.image.repository }}:{{ .Values.cliente.image.tag }}"
          # ... otras configuraciones del contenedor cliente ...

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-app
spec:
  replicas: {{ .Values.eurekaserver.replicaCount }}
  selector:
    matchLabels:
        app: eureka-app
  template:
    metadata:
      labels:
          app: eureka-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-eurekaserver
          image: "{{ .Values.eurekaserver.image.repository }}:{{ .Values.eurekaserver.image.tag }}"
          # ... otras configuraciones del contenedor eurekaserver ...
